[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[build.watchPatterns]
patterns = ["**/*.py", "requirements.txt"]

[[services]]
name = "beauty-palette-server"